---

- name: Add password to root user
  user:
    name: root
    password: "{{ vault.root_password }}"

- name: Add stanislas user
  user:
    name: stanislas
    groups: sudo
    shell: /usr/bin/fish
    password: "{{ vault.stanislas_password }}"

- name: Creates /home/stanislas/.ssh/ directory
  file:
    path: /home/stanislas/.ssh/
    state: directory
    owner: stanislas
    group: stanislas

- name: Set up SSH authorized keys
  template:
    src: "ssh/authorized_keys.j2"
    dest: "{{ item }}"
  with_items:
    - /root/.ssh/authorized_keys
    - /home/stanislas/.ssh/authorized_keys

- name: Install basic packages
  apt:
    name:
      - fail2ban
      - haveged
      - netdata

- name: Set swappiness to 5
  sysctl:
    name: vm.swappiness
    value: 5
    state: present
    reload: yes
