- name: Add stanislas user
  user:
    name: stanislas
    groups: sudo
    shell: /usr/bin/fish
    password: "{{ vault.stanislas_password }}"

- name: Creates /home/stanislas/.ssh/ directory
  file:
    path: /home/stanislas/.ssh/
    state: directory
    owner: stanislas
    group: stanislas

- name: Set up SSH authorized keys
  template:
    src: ../templates/ssh/authorized_keys.j2
    dest: "{{ item }}"
  with_items:
    - /root/.ssh/authorized_keys
    - /home/stanislas/.ssh/authorized_keys

- name: Install basic packages
  apt:
    name:
      - fail2ban
      - haveged

- name: Install unbound
  when: ansible_distribution == "Debian"
  apt:
    name: unbound

- name: Add Unbound config
  when: ansible_distribution == "Debian"
  copy:
    src: ../files/etc/unbound/unbound.conf
    dest: /etc/unbound/
  notify: unbound reload

- name: Set DNS resolver to Unbound in DHCP config
  when: ansible_distribution == "Debian"
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    regexp: "^prepend domain-name-servers"
    line: "prepend domain-name-servers 127.0.0.1;"

- name: Set swappiness to 5
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^vm.swappiness"
    line: "vm.swappiness = 5"
  register: sysctl

- name: Reload sysctl
  shell: sysctl -p
  when: sysctl.changed
