---
- name: Install locale-gen
  apt:
    update_cache: true
    name:
      - locales

- name: Setup locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_US.UTF-8
    - fr_FR.UTF-8

- name: Set timezone to Europe/Paris
  community.general.timezone:
    name: Europe/Paris

- name: Add sources.list
  ansible.builtin.template:
    src: "etc/apt/sources.list.j2"
    dest: "/etc/apt/sources.list"
    mode: 0644
  notify: update_apt_cache

- name: Install basic packages
  apt:
    update_cache: true
    name:
      - fish
      - vim
      - git
      - tmux
      - nano
      - htop
      - curl
      - wget
      - sudo
      - strace
      - iftop
      - jnettop
      - iotop
      - nload
      - ioping
      - reptyr
      - tree
      - ncdu
      - zip
      - unzip
      - time
      - dialog
      - apt-utils
      - screen
      - vnstat
      - man-db
      - python3-pip
      - dnsutils
      - telnet
      - tcpdump
      - traceroute
      - mtr
      - nmap
      - lsof
      - apt-transport-https
      - pigz
      - uptimed
      - ethstatus
      - ca-certificates
      - logrotate
      - rsyslog
      - net-tools
      - rsync
      - jq
      - sysstat
      - unattended-upgrades
      - fail2ban
      - haveged
      - gpg
      - dirmngr
      - gpg-agent

- name: Set fish as the root shell
  ansible.builtin.user:
    name: root
    shell: /usr/bin/fish

- name: Add dotfiles
  ansible.builtin.copy:
    src: "root/{{ item }}"
    dest: "/root/"
    mode: 0775
  with_items:
    - .config

- name: Add config.fish
  ansible.builtin.template:
    src: root/.config/fish/config.fish.j2
    dest: /root/.config/fish/config.fish
    mode: 0644

- name: Add rsyslog logrotate without delaycompress
  ansible.builtin.template:
    src: "etc/logrotate.d/rsyslog.j2"
    dest: "/etc/logrotate.d/rsyslog"
    mode: 0644

- name: Install APT dependencies for MOTD
  apt:
    name:
      - figlet
      - ruby

- name: Install Ruby dependencies for MOTD
  gem:
    name: lolcat
    user_install: no

- name: Copy MOTD scripts
  ansible.builtin.copy:
    src: "etc/update-motd.d/{{ item }}"
    dest: "/etc/update-motd.d"
    mode: +x
  with_items:
    - 10-hostname
    - 20-sysinfo
    # - 30-apt

- name: Make sure /etc/motd is empty
  ansible.builtin.copy:
    content: ""
    dest: "/etc/motd"
    mode: 0644

- name: Install unbound
  when: ansible_distribution == "Debian" and inventory_hostname not in groups['pve']
  apt:
    name: unbound

- name: Add Unbound config
  when: ansible_distribution == "Debian" and inventory_hostname not in groups['pve']
  ansible.builtin.template:
    src: "etc/unbound/unbound.conf.j2"
    dest: "/etc/unbound/unbound.conf"
    mode: 0644
  notify: unbound restart

- name: Set DNS resolver to Unbound in DHCP config
  when: ansible_distribution == "Debian" and inventory_hostname not in groups['pve']
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    regexp: "^prepend domain-name-servers"
    line: "prepend domain-name-servers 127.0.0.1;"

- name: Add vimrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wklken/vim-for-server/master/vimrc
    dest: /root/.vimrc

- name: Add password to root user
  ansible.builtin.user:
    name: root
    password: "{{ vault.root_password }}"

- name: Add stanislas user
  ansible.builtin.user:
    name: stanislas
    groups: ["sudo"]
    shell: /usr/bin/fish
    password: "{{ vault.stanislas_password }}"

- name: Creates /home/stanislas/.ssh/ directory
  ansible.builtin.file:
    path: /home/stanislas/.ssh/
    state: directory
    owner: stanislas
    group: stanislas
    mode: 0700

- name: Set up SSH authorized keys
  ansible.builtin.template:
    src: "ssh/authorized_keys.j2"
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - /root/.ssh/authorized_keys
    - /home/stanislas/.ssh/authorized_keys

- name: Copy unattended-upgrades configuration
  ansible.builtin.copy:
    src: "etc/apt/apt.conf.d/{{ item }}"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    mode: 0644
  with_items:
    - "50unattended-upgrades"
    - "20auto-upgrades"

- name: Configure private network interface
  ansible.builtin.template:
    src: "etc/network/interfaces.d/priv.cfg.j2"
    dest: "/etc/network/interfaces.d/priv.cfg"
    mode: 0644
  when: private_network_address is defined
  notify: network restart
  tags: base.network

- name: Configure private network interface
  ansible.builtin.template:
    src: "etc/udev/rules.d/75-persistent-net-generator.rules.j2"
    dest: "/etc/udev/rules.d/75-persistent-net-generator.rules"
    mode: 0644
  when: private_network_interface_mac is defined
  tags: base.network
