---

- import_tasks: common.yml

- import_tasks: host.yml
  when:
    - "'host' in groups"
    - inventory_hostname in groups['host']

- import_tasks: lxd.yml
  when:
    - "'lxd' in groups"
    - inventory_hostname in groups['lxd']
