---

- name: Setup locales
  locale_gen:
    name: '{{ item }}'
    state: present
  with_items:
    - en_US.UTF-8
    - fr_FR.UTF-8

- name: Set timezone to Europe/Paris
  timezone:
    name: Europe/Paris

- name: Install basic packages
  apt:
    name:
      - fish
      - vim
      - git
      - tmux
      - nano
      - htop
      - curl
      - wget
      - sudo
      - strace
      - iftop
      - jnettop
      - iotop
      - nload
      - ioping
      - reptyr
      - tree
      - ncdu
      - zip
      - unzip
      - time
      - dialog
      - apt-utils
      - screen
      - vnstat
      - man-db
      - python-pip
      - python3-pip
      - dnsutils
      - telnet
      - tcpdump
      - traceroute
      - mtr
      - nmap
      - lsof
      - apt-transport-https
      - pigz
      - uptimed
      - ethstatus

- name: Set fish as the root shell
  user:
    name: root
    shell: /usr/bin/fish

- name: Add password to root user
  user:
    name: root
    password: "{{ vault.root_password }}"

- name: Add dotfiles
  copy:
    src: ../files/root/{{ item }}
    dest: /root/
  with_items:
    - .config

- name: Add dotfiles (template)
  copy:
    src: ../templates/root/{{ item }}
    dest: /root/
  with_items:
    - .config

- name: Add sources.list
  template:
    src: ../templates/etc/apt/sources.list.j2
    dest: /etc/apt/sources.list

- name: Add rsyslog logrotate without delaycompress
  copy:
    src: ../files/etc/logrotate.d/rsyslog
    dest: /etc/logrotate.d/

- name: Install APT dependencies for MOTD
  apt:
    name:
      - figlet
      - ruby

- name: Install Ruby dependencies for MOTD
  gem:
    name: lolcat
    user_install: no

- name: Copy MOTD scripts
  copy:
    src: ../files/etc/update-motd.d/{{ item }}
    dest: /etc/update-motd.d
    mode: +x
  with_items:
      - 10-hostname
      - 20-sysinfo
      - 30-apt

- name: Make sure /etc/motd is empty
  copy:
    content: ""
    dest: /etc/motd

- import_tasks: host.yml
  when: inventory_hostname not in groups['lxd']

- import_tasks: lxd.yml
  when: inventory_hostname in groups['lxd']
