---
- name: unbound restart
  service:
    name: unbound
    state: restarted

- name: update_apt_cache
  apt:
    update_cache: yes

- name: network restart
  service:
    name: networking
    state: restarted
